server {
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    listen 80;
    server_name _;
    index index.html;

    location / {
        # 内容位置
        root /app;

        # 完全匹配 -> 反向清理 url -> 文件夹 -> 没有发现    
        try_files $uri $uri.html $uri/ =404;

        # 不存在的页面
        error_page 404 /404.html;

        # 在此设置中，如果文件夹没有 index.html，就会引发 403 错误
        error_page 403 /404.html;

        # 调整缓存标头
        # assets 文件夹中的文件都有哈希文件名
        location ~* ^/assets/ {
            expires 1y;
            add_header Cache-Control "public, immutable";
        }
    }
}